name: Infracost_custom

on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - main
env:
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Run Infracost for AWS EC2 instances
        run: |
          infracost breakdown --path . --format json > infracost_output.json
          realpath infracost_output.json

      - name: Extract Resource Costs
        run: |
          cat infracost_output.json
          # Extract the cost of each resource
          cat infracost_output.json | jq -r '.projects[1].resources[] | "\(.name): \(.monthly_cost)"' > resource_costs.txt

      - name: Display Resource Costs
        run: |
          cat resource_costs.txt

      - name: Run Custom Policy
        run: |
          bash custom_policy_infracost.sh
