name: Terraform with synk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g snyk

      - name: Run Snyk scan
        run:  snyk auth
        env:
           SNYK_TOKEN: 0decde59-5cd1-4aa4-a3dd-851bdef0c0fd
          # ${{ secrets.SNYK_TOKEN }}
                  # run: snyk test --all-projects


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
