name: CloudSploit Scan

on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install CloudSploit CLI
        run: |
          npm install -g cloudsploit-cli  # Install the CloudSploit CLI globally
          cloudsploit-cli --version       # Verify installation

      # - name: Run CloudSploit Scan
      #   run: |
      #     cloudsploit-cli scan --config config.yaml

      # - name: Process Scan Results
      #   run: |
      #     # Process the scan results here
      #     # You might want to create GitHub issues, send notifications, etc.
