name: Terraform with synk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Infrastructure Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./i
    env:
      TF_WORKSPACE: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Snyk
        run: |
          npm install -g snyk
          echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}"
    
      - name: Vulnerability scan
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
      - name: Upload sarif file to Github Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v2

      # - name: Run Snyk scan
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   run: snyk test --all-projects


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
