name: Infracost_thershold

on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - main
env:
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Run Infracost
        run: |
          infracost breakdown --path . --format json > infracost_output.json
          cat infracost_output.json
          realpath infracost_output.json

      - name: Show Infracost Usage
        run: |
          cat /home/runner/work/terraform/terraform/infracost_output.json  # Display the contents of the usage file (optional)

      - name: script Threshold
        run: |
            #!/bin/bash

            # Use jq to extract the totalMonthlyCost value from the last dictionary in the JSON file
            totalMonthlyCost=$(jq '. | map(.totalMonthlyCost) | last' infracost_output.json)

            # Print the value
            echo "Total Monthly Cost: $totalMonthlyCost"




      - name: Check Cost Threshold
        run: |
          threshold=0
          cost=$(cat /home/runner/work/terraform/terraform/infracost_output.json | jq '.[].totalMonthlyCost | tonumber')
          if (( $(echo "$cost > $threshold" | bc -l) )); then
            echo "Error: Estimated cost ($cost) exceeds the threshold of $threshold"
            exit 1
          fi
