name: Infracost_basic

on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - main
env:
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  infracost:
    name: Check Infrastructure Costs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Infracost
        run: |
          curl -fsSL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz
          sudo mv infracost-linux-amd64 /usr/local/bin/infracost

      - name: Run Infracost
        run: infracost breakdown --path . 